import { Box, Stack } from "@mui/material";
import Head from "next/head";
import React from "react";
import DataTable from "../../components/dataTable/DataTable";

type DoctorsProps = {};

const Doctors: React.FC<DoctorsProps> = () => {
  return (
    <>
      <Head>
        <title>Doctors - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>

      <Stack>
        <Box>
          <DataTable doctor />
        </Box>
      </Stack>
    </>
  );
};
export default Doctors;
