import { Box, Button, Flex, Image, Input, Stack, Text } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";

type RegisterProps = {};

const Register: React.FC<RegisterProps> = () => {
  const [registerForm, setRegisterForm] = useState({
    name: "",
    desc: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setRegisterForm((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
  };

  return (
    <>
      <Head>
        <title>Register - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <Flex align="center" justify="center" height="100vh" gap="15px">
        <Box flex={1} h="100%" display={{ base: "none", md: "unset" }}>
          <Image h="100%" objectFit="cover" src="/img/pattern.png" alt="" />
        </Box>

        <Stack flex={2} padding="0 35px">
          <form onSubmit={handleSubmit}>
            <Stack
              align="center"
              width={{ base: "100%", md: "450px" }}
              gap="20px"
              margin="0px auto"
            >
              <Text fontWeight={600} fontSize="28px" color="brand.100">
                Register
              </Text>

              <Input
                type="text"
                name="name"
                placeholder="Hospital Name"
                height="50px"
                width="100%"
                _focus={{ border: "1px solid #27c399" }}
                onChange={handleChange}
              />

              <Input
                type="text"
                name="desc"
                placeholder="Description"
                height="50px"
                width="100%"
                _focus={{ border: "1px solid #27c399" }}
                onChange={handleChange}
              />

              <Box w="100%">
                <Input
                  type="email"
                  name="email"
                  placeholder="Email"
                  height="50px"
                  width="100%"
                  _focus={{ border: "1px solid #27c399" }}
                  onChange={handleChange}
                />
                <Text
                  fontSize="10pt"
                  color="gray.300"
                  padding="10px 5px"
                  pb={0}
                >
                  Enter the professional email address of your hospital.
                </Text>
              </Box>

              <Input
                type="password"
                name="password"
                placeholder="Password"
                height="50px"
                width="100%"
                _focus={{ border: "1px solid #27c399" }}
                onChange={handleChange}
              />

              <Input
                type="password"
                name="confirmPassword"
                placeholder="Confirm Password"
                height="50px"
                width="100%"
                _focus={{ border: "1px solid #27c399" }}
                onChange={handleChange}
              />

              <Flex align="center" gap="5px">
                <Text>Already have an account?</Text>
                <Link href="/login">
                  <Button variant="link">Login</Button>
                </Link>
              </Flex>

              <Button width="100%" type="submit">
                Register
              </Button>
            </Stack>
          </form>
        </Stack>

        <Box flex={1} h="100%" display={{ base: "none", md: "unset" }}>
          <Image h="100%" objectFit="cover" src="/img/pattern.png" alt="" />
        </Box>
      </Flex>
    </>
  );
};
export default Register;
