import Head from "next/head";
import React from "react";
import ReactECharts from "echarts-for-react";
import * as echarts from "echarts";
import {
  Groups2,
  Groups3,
  HealthAndSafety,
  Inventory,
} from "@mui/icons-material";
import StatusCard from "../../components/statusCard/StatusCard";
import { Grid } from "@mui/material";

type DashboardProps = {};

const statusCard = [
  {
    icon: <Groups2 sx={{ fontSize: "40px" }} />,
    count: "80+",
    title: "PATIENTS",
  },
  {
    icon: <Groups3 sx={{ fontSize: "30px" }} />,
    count: "25+",
    title: "DOCTORS",
  },
  {
    icon: <Inventory sx={{ fontSize: "30px" }} />,
    count: "100+",
    title: "STOCKS",
  },
  {
    icon: <HealthAndSafety sx={{ fontSize: "30px" }} />,
    count: "70+",
    title: "HEALTH CARE",
  },
];

const Dashboard: React.FC<DashboardProps> = () => {
  const option = {
    color: ["var(--accent-color)"],

    toolbox: {
      feature: {
        saveAsImage: {},
      },
    },

    tooltip: {
      trigger: "axis",
      axisPointer: {
        type: "cross",
      },
      backgroundColor: "rgba(0, 0, 0, 0.59)",
      borderWidth: 0,
    },
    grid: {
      left: "3%",
      right: "4%",
      bottom: "3%",
      containLabel: true,
      show: false,
    },

    xAxis: [
      {
        type: "category",
        boundaryGap: false,
        data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
      },
    ],
    yAxis: [
      {
        type: "value",
        splitLine: {
          show: false,
        },
      },
    ],
    series: [
      {
        type: "line",
        smooth: true,
        lineStyle: {
          color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
            {
              offset: 0,
              color: "#27c399",
            },
            {
              offset: 1,
              color: "#24584a",
            },
          ]),
          width: 4,
        },
        areaStyle: {
          opacity: 0.5,
          color: new echarts.graphic.LinearGradient(0, 0, 0, 0.8, [
            {
              offset: 0,
              color: "#27c399",
            },
            {
              offset: 1,
              color: "rgba(95, 253, 211, 0.1)",
            },
          ]),
        },
        emphasis: {
          focus: "series",
        },
        showSymbol: false,
        data: [28000, 19000, 32000, 18000, 41000, 30000, 26000],
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Dashboard - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <Grid
        container
        spacing={{ xs: 2, md: 3 }}
        columns={{ xs: 4, sm: 8, md: 8 }}
        padding="40px 0px 30px 0px"
      >
        {statusCard?.map((item, i) => (
          <StatusCard key={i} item={item} />
        ))}
      </Grid>

      <ReactECharts
        style={{ width: "100%", overflow: "hidden" }}
        option={option}
      />
    </>
  );
};

export default Dashboard;
