import Head from "next/head";
import React from "react";

type DashboardProps = {};

const Dashboard: React.FC<DashboardProps> = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <div>Dashboard</div>
    </>
  );
};

export default Dashboard;
