import Head from "next/head";
import React from "react";
import { Stack } from "@mui/material";
import Header from "../../components/header/Header";

type DashboardProps = {};

const Dashboard: React.FC<DashboardProps> = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <Stack p="30px">
        <Header title="Dashboard" />
      </Stack>
    </>
  );
};

export default Dashboard;
