import {
  Backdrop,
  Button,
  Checkbox,
  CircularProgress,
  FormControlLabel,
  MenuItem,
  Stack,
  TextField,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { ChangeEvent, FormEvent, useEffect, useState } from "react";
import useHospitalData from "../../../../hooks/useHospitalData";
import { doc, getDoc, serverTimestamp, updateDoc } from "firebase/firestore";
import { firestore } from "../../../../firebase/clientApp";
import { PatientDetails } from "../../../../../types";

type EditPatientDetailsProps = {};

const EditPatientDetails: React.FC<EditPatientDetailsProps> = () => {
  const { hospitalStateValue } = useHospitalData();
  const hospitalData = hospitalStateValue.hospitalData;
  const { patientId } = useRouter().query;
  const [patientDetails, setPatientDetails] = useState<PatientDetails>();
  const [formInput, setFormInput] = useState({
    fullname: "",
    phone: "",
    email: "",
    age: "",
    gender: "",
    bloodGroup: "",
    height: "",
    weight: "",
    symptoms: "",
    prescribedMed: "",
    address: "",
    addInfo: "",
  });
  const [highPres, setHighPres] = useState(false);
  const [lowPres, setLowPres] = useState(false);
  const [diabetic, setDiabetic] = useState(false);
  const [smoker, setSmoker] = useState(false);

  const [loading, setLoading] = useState(false);
  const [fetching, setFetching] = useState(false);
  const router = useRouter();

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    e.preventDefault();
    setFormInput((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const getPatientDetails = async () => {
    try {
      setFetching(true);
      const patientDocRef = doc(
        firestore,
        `/hospitals/${hospitalData.username}/patients/${patientId}`
      );
      const patientDoc = await getDoc(patientDocRef);

      if (patientDoc.exists()) {
        setPatientDetails({
          id: patientDoc.id,
          ...patientDoc.data(),
        } as PatientDetails);
      } else {
        console.log("No such document!");
      }
      setFetching(false);
    } catch (error) {
      console.log("getPatientDetails Error", error);
    }
  };

  const handleEditSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    try {
      setLoading(true);
      const patientDocRef = doc(
        firestore,
        `/hospitals/${hospitalData.username}/patients/${patientId}`
      );
      await updateDoc(patientDocRef, {
        ...formInput,
        highPres,
        lowPres,
        diabetic,
        smoker,
        createdAt: serverTimestamp(),
      });

      router.push(`/patient/${patientId}`);
      setLoading(false);
    } catch (error) {
      console.log("handleEditSubmit Error", error);
    }
  };

  useEffect(() => {
    getPatientDetails();
    setFormInput((prev) => ({
      ...prev,
      fullname: patientDetails?.fullname!,
      phone: patientDetails?.phone!,
      email: patientDetails?.email!,
      age: patientDetails?.age!,
      gender: patientDetails?.gender!,
      bloodGroup: patientDetails?.bloodGroup!,
      height: patientDetails?.height!,
      weight: patientDetails?.weight!,
      symptoms: patientDetails?.symptoms!,
      prescribedMed: patientDetails?.prescribedMed!,
      address: patientDetails?.address!,
      addInfo: patientDetails?.addInfo!,
    }));
    setHighPres(patientDetails?.highPres!);
    setLowPres(patientDetails?.lowPres!);
    setDiabetic(patientDetails?.diabetic!);
    setSmoker(patientDetails?.smoker!);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [patientId, patientDetails?.id]);

  console.log(patientDetails);

  return (
    <>
      <Head>
        <title>
          Edit{" "}
          {patientDetails?.fullname
            ? `${patientDetails.fullname}'s`
            : "Loading"}{" "}
          Details - Medzzy!
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      {fetching && (
        <Backdrop
          sx={{ color: "#fff", zIndex: (theme) => theme.zIndex.drawer + 1 }}
          open={fetching}
        >
          <CircularProgress color="inherit" />
        </Backdrop>
      )}

      <Stack margin="30px 0px">
        <Stack flexDirection="row">
          <form className="form" onSubmit={handleEditSubmit}>
            <TextField
              type="text"
              label="Patient's Name"
              name="fullname"
              placeholder="Patient's Name"
              className="formInput"
              value={formInput.fullname}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Phone number"
              name="phone"
              placeholder="Phone number"
              className="formInput"
              value={formInput.phone}
              onChange={handleChange}
            />
            <TextField
              type="email"
              label="Email"
              name="email"
              placeholder="Email"
              className="formInput"
              value={formInput.email}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Age"
              name="age"
              placeholder="Age"
              className="formInput"
              value={formInput.age}
              onChange={handleChange}
            />

            <TextField
              select
              type="text"
              label="Gender"
              name="gender"
              placeholder="Gender"
              className="formInput"
              value={formInput.gender}
              onChange={handleChange}
            >
              <MenuItem value="Male">Male</MenuItem>
              <MenuItem value="Female">Female</MenuItem>
              <MenuItem value="Others">Others</MenuItem>
            </TextField>

            <TextField
              select
              type="text"
              label="Blood group"
              name="bloodGroup"
              placeholder="Blood group"
              className="formInput"
              value={formInput.bloodGroup}
              onChange={handleChange}
            >
              <MenuItem value="O +ve">O +ve</MenuItem>
              <MenuItem value="O -ve">O -ve</MenuItem>
              <MenuItem value="A +ve">A +ve</MenuItem>
              <MenuItem value="A -ve">A -ve</MenuItem>
              <MenuItem value="B +ve">B +ve</MenuItem>
              <MenuItem value="B -ve">B -ve</MenuItem>
              <MenuItem value="AB +ve">AB +ve</MenuItem>
              <MenuItem value="AB -ve">AB -ve</MenuItem>
            </TextField>

            <TextField
              type="text"
              label="Height"
              name="height"
              placeholder="Height"
              className="formInput"
              value={formInput.height}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Weight"
              name="weight"
              placeholder="Weight"
              className="formInput"
              value={formInput.weight}
              onChange={handleChange}
            />

            <TextField
              type="text"
              label="Symptoms"
              name="symptoms"
              placeholder="Symptoms"
              multiline
              rows={3}
              className="formInput"
              value={formInput.symptoms}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Prescribed Medicines"
              name="prescribedMed"
              placeholder="Prescribed Medicines"
              multiline
              rows={3}
              className="formInput"
              value={formInput.prescribedMed}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Address"
              name="address"
              placeholder="Address"
              multiline
              rows={3}
              className="formInput"
              value={formInput.address}
              onChange={handleChange}
            />
            <TextField
              type="text"
              label="Additional Info"
              name="addInfo"
              placeholder="Additional Info"
              multiline
              rows={3}
              className="formInput"
              value={formInput.addInfo}
              onChange={handleChange}
            />

            <Stack
              flexDirection="row"
              alignItems="center"
              justifyContent="space-between"
              width="100%"
              flexWrap="wrap"
              margin="10px 0px"
            >
              <FormControlLabel
                control={
                  <Checkbox
                    name="highPres"
                    checked={highPres}
                    onChange={(e) => setHighPres(e.target.checked)}
                  />
                }
                label="High Pressure"
              />
              <FormControlLabel
                control={
                  <Checkbox
                    name="lowPres"
                    checked={lowPres}
                    onChange={(e) => setLowPres(e.target.checked)}
                  />
                }
                label="Low Pressure"
              />
              <FormControlLabel
                control={
                  <Checkbox
                    name="diabetic"
                    checked={diabetic}
                    onChange={(e) => setDiabetic(e.target.checked)}
                  />
                }
                label="Diabetic"
              />
              <FormControlLabel
                control={
                  <Checkbox
                    name="smoker"
                    checked={smoker}
                    onChange={(e) => setSmoker(e.target.checked)}
                  />
                }
                label="Smoker"
              />
            </Stack>

            <Button
              sx={{
                backgroundImage: "var(--bg-gradient)",
                color: "white",
                fontWeight: 600,
                borderRadius: "25px",
                padding: "8px 40px",
                marginTop: "15px",
              }}
              type="submit"
            >
              {loading ? (
                <CircularProgress
                  color="inherit"
                  size="20px"
                  sx={{ margin: "0px 20px" }}
                />
              ) : (
                "Submit"
              )}
            </Button>
          </form>
        </Stack>
      </Stack>
    </>
  );
};
export default EditPatientDetails;
