import Head from "next/head";
import { Box, Stack } from "@mui/material";
import React from "react";
import DataTable from "../../components/dataTable/DataTable";

type PatientsProps = {};

const Patients: React.FC<PatientsProps> = () => {
  return (
    <>
      <Head>
        <title>Patients - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>

      <Stack>
        <Box>
          <DataTable />
        </Box>
      </Stack>
    </>
  );
};
export default Patients;
