import { Box, Stack } from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import Header from "../../components/header/Header";

type indexProps = {};

const index: React.FC<indexProps> = () => {
  return (
    <>
      <Head>
        <title>Patients - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <Stack p="30px">
        <Header title="Patients" />
      </Stack>
    </>
  );
};
export default index;
