import Head from "next/head";
import { Stack } from "@mui/material";
import React from "react";
import Header from "../../components/header/Header";
import DataTable from "../../components/dataTable/DataTable";

type indexProps = {};

const index: React.FC<indexProps> = () => {
  return (
    <>
      <Head>
        <title>Patients - Medzzy!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.svg" />
      </Head>

      <Stack p="30px">
        <Header title="Patients" />

        <DataTable />
      </Stack>
    </>
  );
};
export default index;
